<?php

declare(strict_types=1);

namespace EventTao;

use pocketmine\plugin\PluginBase;

class Main extends PluginBase{

    protected function onEnable(): void
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }
}